title: "Francisco Jose Nardi Filho"
url: "https://francisnardi.github.io"
baseurl: ""

name: "Francisco Jose Nardi Filho"
tagline: "Senior Software Engineer | Technical Leader | Financial Systems Specialist"
email: "francisnardi@gmail.com"
phone: "+55 (11) 98362-8217"
website: "https://sites.google.com/view/fnardif"
linkedin: "https://linkedin.com/in/francisnardi"
github: "https://github.com/francisnardi"
address: "Sebastião de Souza 50, Guaranésia, MG, Brazil"
nationality: "European (Italian) / Brazilian"

about: "Senior Software Engineer with over 8 years of experience in financial systems, back-end development, and cloud infrastructure. I excel in designing scalable software, leading technical teams, and aligning technical solutions with business goals. My objective is to contribute to innovative, data-driven solutions in the financial domain."

skills:
  - "Python"
  - "Financial Systems"
  - "Cloud Infrastructure (AWS, Azure)"
  - "Data Engineering"
  - "Risk Management"
  - "DevOps & CI/CD"
  - "Workflow Orchestration (Airflow)"
  - "C#"
  - "Go"
  - "SQL"

show_experience: true
show_education: true
show_projects: true
show_skills: true

sass:
  sass_dir: _sass
  style: compressed